server: redis

influxdb:
  returnType: influxdb
  url: http://127.0.0.1:8086/
  username: CHANGE_ME_INFLUXDB_USER
  password: CHANGE_ME_INFLUXDB_PASSWORD

redis:
  returnType : redis
  host: 127.0.0.1
  port: 6379

app: nebula
