#define in nebula.conf
#babal_server = redis

#redis_host = 127.0.0.1
#redis_port = 6379

#metrics_server =redis

#---------
influxdb_url = http://127.0.0.1:9001/metricsproxy/
influxdb_username = CHANGE_ME_INFLUXDB_USER
influxdb_password = CHANGE_ME_INFLUXDB_PASSWORD

#define in monitor.properties
app = monitor

db_path = /home/threathunter/nebula/monitor/monitor.db
db_service = sqlite


mail_sender = alert@example.com
administrator = alert@example.com
mail_host = mail.example.com
mail_username=alert@example.com
mail_password=CHANGE_ME_SMTP_PASSWORD

nebula.system.disk.main=/home/threathunter/nebula
nebula.system.disk.data=/data

mail_enable = false
